options:
  zone:
    default: "rebaca.local"
    description: "The DNS root zone for this service"
    type: string
  tags:
    type: string
    default: "local-commands"
    description: "Tag for the feature file to run"
  abot_app:       
    type: string
    default: "abot-ims-basic"
    description: "The ABot Application"
  abot_version:
    type: string
    default: "3.1.0"
    description: "The ABot Version"

