options:
   branch:
     default: "v0.3.2-branch"
     description: |
       branch indicates which installation you want to do. If you want an stable installation, change this option to "master". 
     type: string
   revision: 
     default: "HEAD"   
     description: get a specific revison from the openair-cn git repository. 
     type: string
   realm:
     default: "openair4G.eur"
     description: |
       Diameter realm of the MME. HSS and EPC have to have the same. NO empty value.
     type: string
   operator-key:
     default: "b3422e065cf199b6f68b470a0f020610"
     description: |
       Operator key for hss . Deafult value is empty.
     type: string
   random:
     default: "true"
     description: |
       Random key flag for hss.
     type: string
   imsi:
     default: "208930100001111"
     description: |
       imsi key for hss
     type: string
