#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)
set -ex

DIR=/etc/rebaca-test-suite
TAG_DIR=/etc/rebaca-test-suite/tags
MAVEN_USER_DIR=/root/.m2
PROXY_ADDRESS=`echo $http_proxy | cut -d'/' -f3 | cut -d':' -f2`
PROXY_PORT=`echo $http_proxy | cut -d'/' -f3 | cut -d':' -f1`

#rm -f $DIR/tags
tags=$(config-get tags)

if [ -n $TAG_DIR/tags ]; then
        # Install the user's supplied hashes
       if [ -f $TAG_DIR/tags ]; then
         existing_tags=`cat $TAG_DIR/tags`
         juju-log "Current tags: $existing_tags"
       fi
       juju-log "Installing the tags obtained from config: $tags"
        echo -n "@$tags" > $TAG_DIR/tags
fi

touch $DIR/sip_server

sip_domain=$(config-get zone)
touch $DIR/sip_domain
if [ ! -z $sip_domain ] ; then
  juju-log "Setting sip_domain=$sip_domain"
  # Install the user's supplied hashes
  echo -n "$sip_domain" > $DIR/sip_domain
fi


diameter_origin_realm=$(config-get zone)
if [ ! -z $diameter_origin_realm ]; then
   juju-log "Setting origin realm=$diameter_origin_realm"
   sed -i "s/ABOT_HSS.OriginRealm=[^ ]*/ABOT_HSS.OriginRealm=$diameter_origin_realm/" $CHARM_DIR/lib/config/config.properties
fi

touch $DIR/ims_hss_mirror_ip
if [ ! -z `cat $DIR/ims_hss_mirror_ip` ]; then
   ims_hss_mirror_ip=`cat $DIR/ims_hss_mirror_ip`
   sed -i "s/HSS_MIRROR.Host.IPAddress=[^ ]*/HSS_MIRROR.Host.IPAddress=$ims_hss_mirror_ip/" $CHARM_DIR/lib/config/config.properties
fi

touch $DIR/ims_cscf_ip
if [ ! -z `cat $DIR/ims_cscf_ip` ]; then
  ims_cscf_ip=`cat $DIR/ims_cscf_ip`
  sed -i "s/P_CSCF.Host.IPAddress=[^ ]*/P_CSCF.Host.IPAddress=$ims_cscf_ip/" $CHARM_DIR/lib/config/config.properties
fi

clearwater_sipp_ip=$(config-get clearwater_sipp_ip)
touch $DIR/clearwater_sipp_ip
if [ -n $DIR/clearwater_sipp_ip ]; then
     if [ ! -z $clearwater_sipp_ip ]; then
        juju-log "Setting clearwater_sipp_ip=$clearwater_sipp_ip"
        # Install the user's supplied hashes
        echo -n "$clearwater_sipp_ip" > $DIR/clearwater_sipp_ip
        sed -i "s/SIPP.Host.IPAddress=[^ ]*/SIPP.Host.IPAddress=$clearwater_sipp_ip/" $CHARM_DIR/lib/config/config.properties
    else
       if [ ! -z `cat $DIR/clearwater_sipp_ip` ]; then
         clearwater_sipp_ip=`cat $DIR/clearwater_sipp_ip`
         sed -i "s/SIPP.Host.IPAddress=[^ ]*/SIPP.Host.IPAddress=$clearwater_sipp_ip/" $CHARM_DIR/lib/config/config.properties
       fi
    fi
fi


#public_address=$(unit-get public-address)
private_address=$(unit-get private-address)
#ip=`dig +short $ip`
if [[ `dig +short $private_address` =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
   then
   juju-log "Verifying $private_address in dns "
    DIGSHORT="dig +short"
 elif [[  "$private_address" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
   then
   DIGSHORT=echo
 else
    juju-log "Unable to fetch private_address ..."
    exit 1
fi

ip=`$DIGSHORT $private_address`

if [ ! -z $ip ]; then
  sed -i "s/ABOT.Host.IPAddress=[^ ]*/ABOT.Host.IPAddress=$ip/" $CHARM_DIR/lib/config/config.properties
else
   juju-log "IP Address of local unit not available - exiting with error"
   exit 2
fi

#Replace realm-name in diameter-specific feature files 
cd $DIR/featureFiles
DOMAIN_NAME="$diameter_origin_realm"
grep -rl rebaca.local . | xargs sed -i "s|rebaca\.local|${DOMAIN_NAME}|g"

#Configure MAVEN proxy
if [  -z $http_proxy ];then
   juju-log "No proxy found"
else
    cat <<EOT > /root/.m2/settings.xml
<settings>
<proxies>
   <proxy>
      <id>optional</id>
      <active>true</active>
      <protocol>http</protocol>
      <username>proxyuser</username>
      <password>proxypass</password>
      <host>$PROXY_ADDRESS</host>
      <port>$PROXY_PORT</port>
      <nonProxyHosts>local.net|some.host.com</nonProxyHosts>
    </proxy>
</proxies>
</settings>
EOT
fi

cd $CHARM_DIR

juju-log "Calling start hook from config-changed hook ..."
. $CHARM_DIR/hooks/start
