#!/bin/bash

set -e

hss_host=`grep "^ABOT.Host.IPAddress" $CHARM_DIR/lib/config/config.properties | cut -d= -f2`
hss_realm=`grep "^ABOT_HSS.OriginRealm" $CHARM_DIR/lib/config/config.properties | cut -d= -f2`

relation-set public-address=$hss_host
relation-set hss-realm=$hss_realm
relation-set hss-port=3868

#if [  -f ~/.ssh/id_rsa.pub ];
#   then
#      ssh_key=`cat ~/.ssh/id_rsa.pub`
#      ssh_key=`echo "$ssh_key" | sed 's/\r//'`
#      relation-set ssh-key=$ssh_key
#fi

