#!/bin/bash

set -e

INTR_ORDER_DIR="/etc/resolvconf"

if [ -f "${INTR_ORDER_DIR}/interface-order.orig" ]; then
    cp ${INTR_ORDER_DIR}/interface-order.orig ${INTR_ORDER_DIR}/interface-order
    resolvconf -u
fi

