#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
set -eu
ABOT_DEPLOY_DIR=/etc/rebaca-test-suite

# Generate ssh key for root user
if [ ! -f /home/ubuntu/.ssh/id_rsa.pub ];
then
    ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa
    pub_key=`cat /root/.ssh/id_rsa.pub`
    echo "${pub_key}" | sed 's/\r//' >> /root/.ssh/authorized_keys
else
    pub_key=`cat /root/.ssh/id_rsa.pub`
    echo "${pub_key}" | sed 's/\r//' >> /root/.ssh/authorized_keys
fi

# Generate ssh key for ubuntu user
if [ ! -f /home/ubuntu/.ssh/id_rsa.pub ];
then
    sudo -u ubuntu bash << EOF
    ssh-keygen -t rsa -N "" -f /home/ubuntu/.ssh/id_rsa
EOF
    pub_key=`cat /home/ubuntu/.ssh/id_rsa.pub`
    echo "${pub_key}" | sed 's/\r//' >> /home/ubuntu/.ssh/authorized_keys
else
    pub_key=`cat /home/ubuntu/.ssh/id_rsa.pub`
    echo "${pub_key}" | sed 's/\r//' >> /home/ubuntu/.ssh/authorized_keys
fi

# Set private address
ip=$(unit-get private-address)
if [[  "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
    juju-log "Private adrress is an IP address - ${ip} . "
    DIGSHORT=echo
elif [[  "${ip}" =~ ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$ ]]
then
    juju-log "Private address is a FQDN - ${ip}  "
    DIGSHORT="dig +short"
else
    juju-log "Unable to find private address "
    exit
fi

ip=`${DIGSHORT} ${ip}`
echo "${ip}"
sed -i "/ip=/s/[^ ]*/ip=${ip}/" ${ABOT_DEPLOY_DIR}/bin/sip

sed -i "/ip=/s/[^ ]*/ip=${ip}/" ${ABOT_DEPLOY_DIR}/bin/sip_imsi_domain

sed -i "/ip=/s/[^ ]*/ip=${ip}/" ${ABOT_DEPLOY_DIR}/bin/sip-stress

status-set maintenance "ABot updated! Setup relations to get into active state..."
