#!/bin/bash
set -e
ABOT_DEPLOY_DIR=/etc/rebaca-test-suite

juju-log "Invoking cscf-relation"
ims_cscf_zone=$(relation-get public-address)
if [ -z "${ims_cscf_zone}" ]; then
    juju-log "No data sent yet from Cscf"
    exit 0
fi

ims_cscf_hostname=$(dig +short _sip._tcp.${ims_cscf_zone} SRV | awk '{print $4}')

juju-log "CSFP FQDN  ${ims_cscf_hostname}"

ims_cscf_ip=`dig +short ${ims_cscf_hostname}`

sed -i "s/P_CSCF.SecureShell.IPAddress=[^ ]*/P_CSCF.SecureShell.IPAddress=${ims_cscf_ip}/" ${ABOT_DEPLOY_DIR}/config/ABotConfig.properties

echo -n ${ims_cscf_hostname} > ${ABOT_DEPLOY_DIR}/sip_server
echo -n ${ims_cscf_ip} > ${ABOT_DEPLOY_DIR}/ims_cscf_ip
echo -n ${ims_cscf_zone} > ${ABOT_DEPLOY_DIR}/sip_domain

if [  -f /home/ubuntu/.ssh/id_rsa.pub ];
then
    ssh_key=`cat /home/ubuntu/.ssh/id_rsa.pub`
    ssh_key=`echo "$ssh_key" | sed 's/\r//'`
    relation-set ssh-key="${ssh_key}"
fi
