#!/bin/bash
set -e

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script hss
pub_key=$(relation-get ssh-key)
echo "$pub_key" >> ~/.ssh/authorized_keys

sudo -u ubuntu bash << EOF
echo "$pub_key" >> ~/.ssh/authorized_keys
EOF

$CHARM_DIR/lib/restart
