#!/bin/bash
set -e
juju-log "Invoking dns-relation"

dns_ip=$(relation-get private-address)
if [ -z "$dns_ip" ]; then
  juju-log "No data sent yet from DNS"
  exit 0
fi

# Set our DNS requirements
id=$(cut -d/ -f2 <<< $JUJU_UNIT_NAME)
ip=$(unit-get private-address)
relation-set domain=$(config-get zone)
DNS_JSON=$($CHARM_DIR/lib/generate_dns_records $ip homestead homestead-$id)
relation-set resources="$DNS_JSON"

# Update our DNS server
if [ "$dns_ip" != "" ]
then
  echo nameserver $dns_ip > /etc/dnsmasq.resolv.conf
  grep -v ^RESOLV_CONF= /etc/default/dnsmasq > /tmp/dnsmasq.$$
  mv /tmp/dnsmasq.$$ /etc/default/dnsmasq
  echo RESOLV_CONF=/etc/dnsmasq.resolv.conf >> /etc/default/dnsmasq
  service dnsmasq restart
fi

# Change Resolvconf order and make dnsmasq on top
dnsmasq=lo.dnsmasq
resolvconf=/etc/resolvconf
loinet=`grep  ^[a-z] /etc/resolvconf/interface-order | head -n1`
 if [ $loinet != $dnsmasq ]
   then
       cp /etc/resolvconf/interface-order /etc/resolvconf/interface-order.orig
          sed  '/'$dnsmasq'/d' /etc/resolvconf/interface-order.orig > /etc/resolvconf/interface-order
          sed -i '/'$loinet'/i lo.dnsmasq' /etc/resolvconf/interface-order
          service dnsmasq restart
          resolvconf -u
 fi

# Verify DNS record to make sure that IMS dns is working properly
if [[ `dig +short $ip` =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
   then
    juju-log "Verifying $ip in dns "
 elif [[ "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
   then
    juju-log "Verifying $ip in dns "
 else
    juju-log "Unable to fetch $ip changing  dns order to original"
  cp /etc/resolvconf/interface-order.orig /etc/resolvconf/interface-order
  resolvconf -u
fi

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple

cassandra_util=/usr/share/clearwater
iter_start=0
loop_count=20
cassandra_change(){
     sed '71,75s/^/ #/' $cassandra_util/cassandra_schema_utils.sh.orig > $cassandra_util/cassandra_schema_utils.sh
     sudo /usr/share/clearwater/cassandra-schemas/homestead_cache.sh
     sudo /usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
     $CHARM_DIR/lib/restart
}


while [ $iter_start -lt $loop_count ]
do
    if  monit status homestead_process | grep "\Execution failed | Does not exist\b"  &&  monit status homestead-prov_process | grep "\Execution failed | Does not exist\b" ; then
       break
    elif  monit status homestead_process | grep "\Running\b" &&  monit status homestead-prov_process | grep "\Running\b"  ; then
      break
    else
        echo "Waiting for monit to be intialized"
        sleep 10
    fi
    iter_start=`expr $iter_start + 1`
done


 if   monit status homestead_process | grep "\Running\b"  &&   monit status homestead-prov_process | grep "\Running\b" ;
       then
         echo juju-log "homestead is running"
        else
          if ! -f "$cassandra_util/cassandra_schema_utils.sh.orig" ;
           then
             cp $cassandra_util/cassandra_schema_utils.sh $cassandra_util/cassandra_schema_utils.sh.orig
             sed '71,75s/^/ #/' $cassandra_util/cassandra_schema_utils.sh.orig > $cassandra_util/cassandra_schema_utils.sh
             /usr/share/clearwater/cassandra-schemas/homestead_cache.sh
             /usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
             service homestead stop
             service homestead-prov stop
           else
             sed '71,75s/^/ #/' $cassandra_util/cassandra_schema_utils.sh.orig > $cassandra_util/cassandra_schema_utils.sh
             /usr/share/clearwater/cassandra-schemas/homestead_cache.sh
             /usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
             service homestead stop
             service homestead-prov stop
         fi
 fi


$CHARM_DIR/lib/restart
