#!/bin/bash

set -e

HSS_HOSTNAME=192.168.40.126
HSS_PORT=3868
HSS_TAG=hss


cat /etc/clearwater/shared_config | grep -v hss_hostname > tmp
sudo cp tmp /etc/clearwater/shared_config
cat /etc/clearwater/shared_config | grep -v hss_realm > tmp
sudo cp tmp /etc/clearwater/shared_config
cat /etc/clearwater/shared_config | grep -v hss_port > tmp
sudo cp tmp /etc/clearwater/shared_config

if [ "$HSS_TAG" == "hss" ]; then
  echo "hss_hostname=$HSS_HOSTNAME" >> tmp
else
  echo "hss_hostname=0.0.0.0" >> tmp
fi

echo "hss_realm="  >> tmp
echo "hss_port=$HSS_PORT"  >> tmp
sudo cp tmp /etc/clearwater/shared_config

rm tmp

sudo service homestead stop
sleep 5

