#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file config-change
# brief manage the config changes of oai-mme service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr and A. B. Molini  

set -ux
source $CHARM_DIR/utils/common
set_env_paths

if [ "$(config-get branch)" != "$(cat $CHARM_DIR/.branch)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "branch changed"
fi

if [ "$(config-get revision)" != "$(cat $CHARM_DIR/.revision)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "revision changed"
fi

if [ "$(config-get kernel)" != "$(cat $CHARM_DIR/.kernel)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
    juju-log "kernel changed"
fi

realm=`config-get realm`
iface=`config-get eth`
max_enb=`config-get maxenb`
max_ue=`config-get maxue`
relative_capacity=`config-get relative_capacity`
mme_statistic_timer=`config-get mme_statistic_timer`
emergency_attach_supported=`config-get emergency_attach_supported`
authenticated_imsi_supported=`config-get authenticated_imsi_supported`
verbosity=`config-get verbosity`
gummei_tai_mcc=`config-get gummei_tai_mcc`
gummei_tai_mnc=`config-get gummei_tai_mnc`
#gummei_tai_tac=`config-get gummei_tai_tac` 
ipv4_list_start=`config-get ipv4_list_start`
ipv4_list_end=`config-get ipv4_list_end`
ipv6_list=`config-get ipv6_list`
DEFAULT_DNS_IPV4_ADDRESS=`config-get DEFAULT_DNS_IPV4_ADDRESS`
DEFAULT_DNS_SEC_IPV4_ADDRESS=`config-get DEFAULT_DNS_SEC_IPV4_ADDRESS`
hss_fqdn=`cat $CHARM_DIR/.hss_fqdn`
spgw_s11_ipv4=`cat $CHARM_DIR/.spgw_s11_ipv4`
local_ip=$(unit-get private-address)
local_private_iface=$(ifconfig | grep -B1 "inet addr:$local_ip" | awk '$1!="inet" && $1!="--" {print $1}')
##############################################################################################

gateway_iface_id=`ip -o -4 route show to default | awk '{print $5}'`

if [[ $gateway_iface_id == $iface ]];then
   iface_verify=`ifconfig $iface | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
   if [ -z $iface_verify ]; then
      br_check=`ifconfig br-eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`;
      eth0_ip_cfg='/etc/network/interfaces.d/eth0.cfg'
      if [ ! -z $br_check ]; then
        br_ip_mask=`ip addr | grep br-eth0 | awk '/inet/ { print $2 }'`
	    br_gateway=`route | awk '/default/ { print $2 }'`
        touch $eth0_ip_cfg
	    echo 'auto eth0' >> $eth0_ip_cfg
	    echo 'iface eth0 inet static' >> $eth0_ip_cfg
	    echo "      address $br_ip_mask" >> $eth0_ip_cfg
	    echo "      gateway $br_gateway" >> $eth0_ip_cfg
	    ifdown eth0 && ifup eth0
      fi
   fi
fi

if ! ifconfig | grep $iface;then
     iface=$local_private_iface
fi

user_conf
systemctl stop mme

if [ "$realm" != "$(cat $CHARM_DIR/.realm)"  ]; then
    rm $freediameter_conf_path/mme.*.pem
    fqdn=`hostname --fqdn`
    $build_run_scripts/check_mme_s6a_certificate $freediameter_conf_path $fqdn

    sed -i "s/`hostname --fqdn`/`hostname`.$realm/" /etc/hosts
    #keep track of the last realm
    echo "$realm" > $CHARM_DIR/.realm 
fi

if [ -z "$(relation-ids hss)" ]; then
    juju-log "MME is built, but is waiting for active connection to gather the last info"
    juju-log "no HSS is found, so MME is not going to be run"
else
    hss_id=`relation-ids hss`
    hss_unit=`relation-list -r $hss_id`
    if [ "$(relation-get -r $hss_id hss_running $hss_unit)" == "yes" ]; then
        juju-log "Relation with HSS exists and it is running, try to run MME"
        $CHARM_DIR/hooks/start
        #status-set active "MME is running and connected to HSS"
        #if hss relation exists
        for mme_id in $(relation-ids mme); do
           restart=`relation-get -r $mme_id trigger_restart $JUJU_UNIT_NAME`
           relation-set -r $mme_id trigger_restart=$(($((restart + 1)) % 10))
           relation-set -r $mme_id mme_running=yes
        done
    else
        juju-log "HSS relation exists, but it is not running because there no database"
        status-set blocked "Add db relation to hss to get MME run.."
    fi
fi
