#!/bin/bash
set -e

pub_key_abotepc=$(relation-get ssh-key-abotepc)
pub_key_abotvolte=$(relation-get ssh-key-abotvolte)

echo "$pub_key_abotepc" >> ~/.ssh/authorized_keys
echo "$pub_key_abotvolte" >> ~/.ssh/authorized_keys

sudo -u ubuntu bash << EOF
echo "$pub_key_abotepc" >> ~/.ssh/authorized_keys
echo "$pub_key_abotvolte" >> ~/.ssh/authorized_keys
EOF


