#!/bin/bash

juju-log "Removing relation with epc"

sed -i "s/ABOT.ENB.mobile_country_code=[^ ]*/ABOT.ENB.mobile_country_code=/" $CHARM_DIR/lib/config/volte_defaults.conf
sed -i "s/ABOT.ENB.mobile_network_code=[^ ]*/ABOT.ENB.mobile_network_code=/" $CHARM_DIR/lib/config/volte_defaults.conf
sed -i "s/ABOT.ENB.mme_ip_address_ipv4=[^ ]*/ABOT.ENB.mme_ip_address_ipv4=192.168.255.255/" $CHARM_DIR/lib/config/volte_defaults.conf
sed -i "s/MME.SecureShell.IPAddress=[^ ]*/MME.SecureShell.IPAddress=192.168.255.255/" $CHARM_DIR/lib/config/ABotConfig.properties
sed -i "s/SPGW.SecureShell.IPAddress=[^ ]*/SPGW.SecureShell.IPAddress=192.168.255.255/" $CHARM_DIR/lib/config/ABotConfig.properties
sed -i -e "s/OPC=\".*\";/OPC=\"\";/" /srv/openair5G/openair3/NAS/TOOLS/ue_eurecom_test_sfr.conf

#Remove the stored value files
rm -f /root/.mme_ip_address_ipv4
rm -f  /root/.spgw_ip_address_ipv4
rm -f /root/.opc_val

status-set blocked "Abot blocked! Waiting for epc relation"
