#!/bin/bash

#called on every epc relation change

set -ex
DIR=/etc/rebaca-test-suite
mobile_country_code=`relation-get MCC`
mobile_network_code=`relation-get MNC`
mme_ip_address_ipv4=`relation-get mme_ip`
mme_running=`relation-get mme_running`
unhex_key=`relation-get opc-key`
spgw_ip_address_ipv4=`relation-get spgw_ip_address_ipv4`

sed -i "s/ABOT.ENB.mobile_country_code=[^ ]*/ABOT.ENB.mobile_country_code=$mobile_country_code/" $CHARM_DIR/lib/config/volte_defaults.conf
sed -i "s/ABOT.ENB.mobile_network_code=[^ ]*/ABOT.ENB.mobile_network_code=$mobile_network_code/" $CHARM_DIR/lib/config/volte_defaults.conf
sed -i "s/ABOT.ENB.mme_ip_address_ipv4=[^ ]*/ABOT.ENB.mme_ip_address_ipv4=$mme_ip_address_ipv4/" $CHARM_DIR/lib/config/volte_defaults.conf
sed -i "s/MME.SecureShell.IPAddress=[^ ]*/MME.SecureShell.IPAddress=$mme_ip_address_ipv4/" $CHARM_DIR/lib/config/ABotConfig.properties
sed -i "s/SPGW.SecureShell.IPAddress=[^ ]*/SPGW.SecureShell.IPAddress=$spgw_ip_address_ipv4/" $CHARM_DIR/lib/config/ABotConfig.properties
sed -i -e "s/OPC=\".*\";/OPC=\"$unhex_key\";/" /srv/openair5G/openair3/NAS/TOOLS/ue_eurecom_test_sfr.conf

echo -n "$mme_ip_address_ipv4" > /root/.mme_ip_address_ipv4
echo -n "$spgw_ip_address_ipv4" > /root/.spgw_ip_address_ipv4
echo -n "$unhex_key" > /root/.opc_val

if [ "$mme_running" == "yes" ]; then
    status-set active "Abot ready! MME relation established, proceed to run tests..."
    exit 0
fi
status-set blocked "Abot blocked! MME relation not established, unable to get to active state"
