#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)
set -e

DIR=/etc/rebaca-test-suite
TAG_DIR=/etc/rebaca-test-suite/tags

#rm -f $DIR/tags
tags=$(config-get tags)

if [ -n $TAG_DIR/tags ]; then
        # Install the user's supplied hashes
       if [ -f $TAG_DIR/tags ]; then
         existing_tags=`cat $TAG_DIR/tags`
         juju-log "Current tags: $existing_tags"
       fi
       juju-log "Installing the tags obtained from config: $tags"
        echo -n "@$tags" > $TAG_DIR/tags
fi

ims_apn_domain=$(config-get ims_apn_domain)
if [ ! -z $diameter_origin_realm ]; then
   juju-log "Setting origin realm=$diameter_origin_realm"
   sed -i "s/ABOT_HSS.OriginRealm=[^ ]*/ABOT_HSS.OriginRealm=$diameter_origin_realm/" $CHARM_DIR/lib/config/config.properties
fi

ims_apn_host=$(config-get ims_apn_host)
tac=$(config-get tac)
mobile_country_code=$(config-get mcc)
mobile_network_code=$(config-get mnc)

sed -i "s/ABOT.ENB.mobile_country_code=[^ ]*/ABOT.ENB.mobile_country_code=$mobile_country_code/" $CHARM_DIR/lib/config/volte_defaults.conf
sed -i "s/ABOT.ENB.mobile_network_code=[^ ]*/ABOT.ENB.mobile_network_code=$mobile_network_code/" $CHARM_DIR/lib/config/volte_defaults.conf
sed -i "s/ABOT.ENB.tracking_area_code=[^ ]*/ABOT.ENB.tracking_area_code=$tac/" $CHARM_DIR/lib/config/volte_defaults.conf

if [ ! -f /root/.mme_ip_address_ipv4 ];then
    touch /root/.mme_ip_address_ipv4
fi
if [ ! -z `cat /root/.mme_ip_address_ipv4` ]; then
     mme_ip_address_ipv4=`cat /root/.mme_ip_address_ipv4`
     sed -i "s/MME.Host.IPAddress=[^ ]*/MME.Host.IPAddress=$mme_ip_address_ipv4/" $CHARM_DIR/lib/config/config.properties
     sed -i "s/ABOT.ENB.mme_ip_address_ipv4=[^ ]*/ABOT.ENB.mme_ip_address_ipv4=$mme_ip_address_ipv4/" $CHARM_DIR/lib/config/volte_defaults.conf  
fi


if [ ! -f /root/.spgw_ip_address_ipv4 ];then
    touch /root/.spgw_ip_address_ipv4
fi

if [ ! -z `cat /root/.spgw_ip_address_ipv4` ]; then
     spgw_ip_address_ipv4=`cat /root/.spgw_ip_address_ipv4`
     sed -i "s/SPGW.Host.IPAddress=[^ ]*/SPGW.Host.IPAddress=$spgw_ip_address_ipv4/" $CHARM_DIR/lib/config/config.properties 
fi


private_address=$(unit-get private-address)
if [[ `dig +short $private_address` =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
    juju-log "Verifying $private_address in dns "
    DIGSHORT="dig +short"
elif [[  "$private_address" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
    DIGSHORT=echo
else
    juju-log "Unable to fetch private_address ..."
    exit 1
fi

ip=`$DIGSHORT $private_address`
  
if [ ! -z $ip ]; then
    sed -i "s/ABOT.Host.IPAddress=[^ ]*/ABOT.Host.IPAddress=$ip/" $CHARM_DIR/lib/config/config.properties
    sed -i "s#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1_MME=[^ ]*#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1_MME=$ip/24#" $CHARM_DIR/lib/config/volte_defaults.conf
    sed -i "s#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1U=[^ ]*#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1U=$ip/24#" $CHARM_DIR/lib/config/volte_defaults.conf
    sed -i "s/ABOT_IP_ADDRESS/$ip/" $CHARM_DIR/lib/abot/static/js/apps/config/appconfig.js
else
    juju-log "IP Address of local unit not available - exiting with error"
    exit 2
fi

#Replace realm-name in diameter-specific feature files 
cd $DIR/featureFiles
DOMAIN_NAME="$ims_apn_domain"
grep -rl rebaca.local . | xargs sed -i "s|rebaca\.local|${DOMAIN_NAME}|g"

echo -n $ims_apn_host > $DIR/sip_server
echo -n $ims_apn_domain > $DIR/sip_domain

#Set IP Address in sip scripts
echo "ue_ip=172.16.0.2"
ue_ip=$(config-get ue_ip)
sed -i "/ip=/s/[^ ]*/ip=$ue_ip/" $DIR/bin/sip
chmod +x $DIR/bin/sip

sed -i "/ip=/s/[^ ]*/ip=$ue_ip/" $DIR/bin/sip_imsi_domain
chmod +x $DIR/bin/sip_imsi_domain

sed -i "/ip=/s/[^ ]*/ip=$ue_ip/" $DIR/bin/sip-stress
chmod +x $DIR/bin/sip-stress
