#!/bin/bash
set -e
DIR=/etc/rebaca-test-suite

juju-log "Invoking hss-relation"
ims_hss_mirror_ip=$(relation-get public-address)
if [ -z "$ims_hss_mirror_ip" ]; then
  juju-log "No data sent yet from HSS"
  exit 0
fi

juju-log "HSS FQDN  $ims_hss_mirror_ip"
if [[ `dig +short $ims_hss_mirror_ip` =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
   then
   juju-log "Verifying $ims_hss_mirror_ip in dns "
    DIGSHORT="dig +short"
 elif [[  "$ims_hss_mirror_ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
   then
   DIGSHORT=echo
 else
    juju-log "Unable to fetch public_address changing  dns order to original"
    exit 1
fi

ims_hss_mirror_ip=`$DIGSHORT $ims_hss_mirror_ip`
juju-log "Ims hss mirror IP $ims_hss_mirror_ip"

if [ -z $ims_hss_mirror_ip ]; then
  juju-log "No IP Address found for HSS_FQDN:  $ims_hss_mirror_ip"
  exit 1
fi

#Update HSS Mirror IP
echo -n "$ims_hss_mirror_ip" > $DIR/ims_hss_mirror_ip
echo -n "$ims_hss_mirror_ip" > /root/.ims_hss_mirror_ip

sed -i "s/HSS_MIRROR.SecureShell.IPAddress=[^ ]*/HSS_MIRROR.SecureShell.IPAddress=$ims_hss_mirror_ip/" $CHARM_DIR/lib/config/ABotConfig.properties
