#!/bin/bash
set -e

if [  -f /home/ubuntu/.ssh/id_rsa.pub ];
   then
      ssh_key=`cat /home/ubuntu/.ssh/id_rsa.pub`
      ssh_key=`echo "$ssh_key" | sed 's/\r//'`
      relation-set ssh-key="$ssh_key"
fi

