#!/bin/bash
# This hook is executed each time a charm is upgraded after the new charm
# contents have been unpacked
# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed
set -eu
DIR=/etc/rebaca-test-suite

abot_volte_basic_url=`config-get abot_volte_basic_repo_url`
abot_volte_basic_package_name=`config-get abot_volte_basic_package`

rm -rf $CHARM_DIR/lib/target
rm -rf $CHARM_DIR/lib/log/*

rm -rf $DIR/*

#Remove the existing version of the abot package
rm -f $CHARM_DIR/payload/abot*.deb

#Download the ABOT package and install it
if [[ ! -d "$CHARM_DIR/payload" ]]; then
    mkdir $CHARM_DIR/payload
fi

wget $abot_volte_basic_url/$abot_volte_basic_package_name -O $CHARM_DIR/payload/$abot_volte_basic_package_name

#Install the package using dpkg
dpkg --install $CHARM_DIR/payload/$abot_volte_basic_package_name
juju-log "Install abot package completed ..."

#Clean out the symlinks from the DIR folder
find $DIR/ -maxdepth 1 -type l -delete

#Create symlinks to installation
mkdir -p $DIR/tags

ln -s $CHARM_DIR/lib/bin $DIR/bin
ln -s $CHARM_DIR/lib/log $DIR/log
ln -s $CHARM_DIR/lib/featureFiles $DIR/featureFiles
ln -s $CHARM_DIR/lib/config $DIR/config
ln -s $CHARM_DIR/lib/jar $DIR/jar
ln -s $CHARM_DIR/lib/scenarios $DIR/scenarios

#Copy oaisim init script
cp $DIR/bin/oaisim.conf /etc/init 

#Change permissions of charm/lib folder
chown -R ubuntu:ubuntu $CHARM_DIR/lib

#Build the oaisim
juju-log "Build oaisim..."
(cd /srv/openair5G/cmake_targets; sudo ./build_oai_rebaca -c -I --oaisim) || true

#Change permissions of the openair5G folders
chown -R ubuntu:ubuntu /srv

open-port 80/tcp

juju-log "ABot update complete!"
status-set maintenance "ABot updated! Reset relations to get into ready state"
