#!/bin/bash
# Action -Run
set -eu

DIR=/etc/rebaca-test-suite/tags
ELASTIC_FILE_NAME=/etc/rebaca-test-suite/es-conf

tags_defined=1
no_report_needed=0

TAG_NAMES=$(action-get tagnames)
TAG_FILE_NAME=$(action-get filename)

if [ ! -z "$TAG_FILE_NAME" ]; then
  juju-log "Tag file specified: $TAG_FILE_NAME"
else
  #Assign default file name
  TAG_FILE_NAME=tags
fi

new_tags=

if [ "$#" -eq  "0" ]; then
   juju-log "No Script input found - may have been called through Juju action"
else 
   TAG_NAMES="$1"
   juju-log " Tag = $1"

   if [ $# -gt 1 ] && [ "$2" == "no-report" ]; then
     no_report_needed=1
   fi
fi

if [ -z "$TAG_NAMES" ]; then
  juju-log "No tag names specified"
  tags_defined=0
  #Check if filename specified and file exists
  if [ ! -z "$TAG_FILE_NAME" ] && [ -f $DIR/$TAG_FILE_NAME ] ; then
      tags=`cat $DIR/$TAG_FILE_NAME`
  fi
else
  juju-log "Tag names: $TAG_NAMES"

  #Split the tags and add the @ symbols
  IFS=', ' read -r -a array <<< "$TAG_NAMES"  
  for index in "${!array[@]}"
  do
    if [ $index -eq 0 ]; then
      new_tags="@${array[0]}"
    else
      #Add current tag only if not duplicate
      current_tag="${array[index]}"
      if [ `echo $new_tags | grep -c $current_tag` -eq 0 ]; then
        new_tags="$new_tags,@$current_tag"
      fi
    fi
  done

  #Assign the tags variable accordingly.
  tags=$new_tags
fi

if [ -z "$tags" ]; then
  juju-log "No tags found for execution"
else
  juju-log "Running the test with the tags $tags"

  cd $CHARM_DIR/lib/
  status-set active  "Executing run action"
  . scripts/tags_update $tags

  #Removing previous run artifacts
  rm -rf $CHARM_DIR/lib/log/*.*

  #Run the install target now
  mvn install -Dtest=RunScenarios -DrootDir=com/rebaca/abot || true

  #Copying log artifacts to appropriate artifacts folder
  LAST_REPORT_DIR="$(ls -td -- ${CHARM_DIR}/lib/artifacts/*/ | head -n 1)"

  if [ $no_report_needed -eq 0 ]; then
    cp -R $CHARM_DIR/lib/log/*.* $LAST_REPORT_DIR
  
    #Process Test results and post to ElasticSearch
    touch $ELASTIC_FILE_NAME
    ES_CONF=`cat $ELASTIC_FILE_NAME`
    if [  -z "$ES_CONF" ]; then
      juju-log "No ES conf defined - hence result not pushed to ES"
    else
      juju-log "Pushing Test result to ES"
      LAST_REPORT_FILE_NAME=`basename $LAST_REPORT_DIR`
      juju-log "Renaming Test result to $LAST_REPORT_FILE_NAME.json"
      cp ${CHARM_DIR}/lib/artifacts/TestResults.json ${CHARM_DIR}/lib/artifacts/$LAST_REPORT_FILE_NAME.json
      python ${CHARM_DIR}/lib/bin/es-feed.py --elastic $ES_CONF  --filepath ${CHARM_DIR}/lib/artifacts/$LAST_REPORT_FILE_NAME.json
    fi
  else
    LAST_REPORT_DATETIME=`basename $LAST_REPORT_DIR`
    cd ${CHARM_DIR}/lib/artifacts
    tar czf ${LAST_REPORT_DATETIME}.tgz $LAST_REPORT_DATETIME
    rm -rf $LAST_REPORT_DATETIME
  fi


  status-set active  "Ready"
fi
