options:
  ims_apn_host:
    default: "bono.rebaca.local"
    description: "The P-CSCF hostname" 
    type: string
  ims_apn_domain:
    default: "rebaca.local"
    description: "The DNS name for ims service"
    type: string
  tac:
    default: "1"
    description: "The default tracking area code for the eNodeB"
    type: string
  mcc:
    default: "208"
    description: "The default broadcast PLMN MCC"
    type: string
  mnc:
    default: "93"
    description: "The default broadcast PLMN MCC"
    type: string
  ue_ip:
    default: "172.16.0.2"
    description: "The SPGW IP Address"
    type: string
  tags:
    type: string
    default: "local-commands"
    description: "Tag for the feature file to run"
  abot_volte_basic_repo_url:
    type: string
    default: "http://115.113.43.202:8090/rebaca"
    description: "URL of abot-volte-basic repo "
  sipp_repo_url:
    type: string
    default: "https://sourceforge.net/projects/sipp/files/sipp/3.3/sipp-3.3.tar.gz"
    description: "URL of sipp repo"
  abot_volte_basic_package:
    type: string
    default: "abot-volte-basic_1.0.0_all.deb"
    description: "The ABot VoLTE Basic package"
  zone:
    default: "rebaca.local"
    description: The DNS root zone for this service
    type: string

    
