options:
  tags:
    type: string
    default: "local-commands"
    description: "Tag for the feature file to run"
  abot_app:       
    type: string
    default: "abot-epc-basic"
    description: "The ABot Application"
  abot_version:       
    type: string
    default: "3.1.1"
    description: "The ABot Version"

