#!/bin/bash
set -e

juju-log "Configuring Cx client"

#AUTH_TYPE=$(action-get auth-type)

if [ "$#" -eq  "0" ]; then
   AUTH_TYPE=$(action-get auth-type)
else
   AUTH_TYPE="$1"
   juju-log " AUTH_TYPE = $1"
fi


CX_CLIENT_IP=`grep "^HSS_MIRROR.Host.IPAddress" $CHARM_DIR/lib/config/config.properties | cut -d= -f2`
if [ -z "$CX_CLIENT_IP" ]; then
  juju-log "HSS hostname not found - exiting"
  exit 0
fi

juju-log "CX_CLIENT_IP=$CX_CLIENT_IP"

ABOT_IP=`grep "^ABOT.Host.IPAddress=" $CHARM_DIR/lib/config/config.properties | cut -d= -f2`
juju-log "ABOT_IP=$ABOT_IP"

CX_CONFIGURATION_SCRIPT=configure_is_cscf
juju-log "Copying configuration script $CX_CONFIGURATION_SCRIPT to $CX_CLIENT_IP"

sed -i "s/HSS_HOSTNAME=[^ ]*/HSS_HOSTNAME=$ABOT_IP/" $CHARM_DIR/lib/scripts/$CX_CONFIGURATION_SCRIPT
sed -i "s/HSS_TAG=[^ ]*/HSS_TAG=$AUTH_TYPE/" $CHARM_DIR/lib/scripts/$CX_CONFIGURATION_SCRIPT

cd $CHARM_DIR/lib/scripts
scp -i /home/ubuntu/.ssh/id_rsa -o StrictHostKeyChecking=no $CX_CONFIGURATION_SCRIPT ubuntu@$CX_CLIENT_IP:/home/ubuntu

ssh -i /home/ubuntu/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$CX_CLIENT_IP /home/ubuntu/$CX_CONFIGURATION_SCRIPT
