#!/bin/bash
# Action -Update Test Scenarios
set -eu

XML_SCENARIO_DIR=/etc/rebaca-test-suite/scenarios

juju-log "Adding new test scenarios into the charm"
#Copy feature files to the relevant folder.
if [ `ls -1 ~ubuntu/test-scenarios | grep feature | wc -l` -gt 0 ]; then
  mv -f ~ubuntu/test-scenarios/*.* $CHARM_DIR/lib/featureFiles/
fi

#Copy SIPP scenario files to the relevant folder.
juju-log "Adding new xml scenarios into the charm"
if [ `ls -1 ~ubuntu/xml-scenarios | grep xml | wc -l` -gt 0 ]; then
  mkdir -p $XML_SCENARIO_DIR
  mv -f ~ubuntu/xml-scenarios/*.xml $CHARM_DIR/lib/scenarios/
  cp -f $CHARM_DIR/lib/scenarios/* $XML_SCENARIO_DIR/
fi
