#!/bin/bash
# Action -Update Framework
set -eu

juju-log "Incorporating new binary files into the Abot framework"
#Copy jar files to the relevant folder.
if [ `ls -1 ~ubuntu/framework-binaries | grep jar | wc -l` -gt 0 ]; then
  mv -f ~ubuntu/framework-binaries/*.jar $CHARM_DIR/lib/jar/

  cd $CHARM_DIR/lib/jar

  echo "Invoking mvn on jar files"
  #Obtain version of base jar
  ABOT_BASE_JAR_FILE=`ls abot-base*.jar`
  ABOT_BASE_VERSION=`ls abot-base*.jar | sed -e "s/abot-base-//g" -e "s/.jar//g"`
  mvn install:install-file -DgroupId=com.rebaca.abot.base -DartifactId=abot-base -Dversion=$ABOT_BASE_VERSION -Dpackaging=jar -Dfile=$CHARM_DIR/lib/jar/$ABOT_BASE_JAR_FILE

  #Obtain version of web jar
  ABOT_WEB_JAR_FILE=`ls abot-web*.jar`
  ABOT_WEB_VERSION=`ls abot-web*.jar | sed -e "s/abot-web-//g" -e "s/.jar//g"`
  mvn install:install-file -DgroupId=com.rebaca.abot.adapters -DartifactId=abot-web -Dversion=$ABOT_WEB_VERSION -Dpackaging=jar -Dfile=$CHARM_DIR/lib/jar/$ABOT_WEB_JAR_FILE

  #Obtain version of diameter jar
  ABOT_DIAMETER_JAR_FILE=`ls abot-diameter*.jar`
  ABOT_DIAMETER_VERSION=`ls abot-diameter*.jar | sed -e "s/abot-diameter-//g" -e "s/.jar//g"`
  mvn install:install-file -DgroupId=com.rebaca.abot.adapters -DartifactId=abot-diameter -Dversion=$ABOT_DIAMETER_VERSION -Dpackaging=jar -Dfile=$CHARM_DIR/lib/jar/$ABOT_DIAMETER_JAR_FILE
fi
