#!/bin/bash

count=0
for name in `find . -type f -name '*.feature'`; 
do
    series=$(grep -i 'Series-[0-9]*' $name | sed 's/.*\([0-9][0-9][0-9][0-9]\).*/\1/')
    if [ "$series" != "" ]  
    then
        new_name=$(echo $name | sed 's?\(.*\)/[0-9][0-9][0-9][0-9]-?\1'/'?')
        new_name=$(echo $new_name | sed 's?\(.*\)/?\1'/"${series}-"'?') 
        if [ "$name" != "$new_name" ]
        then
            echo "Renaming to series - [$series] $new_name"
            mv "$name" "$new_name";
            (( count += 1 ))
        fi
    fi
done
echo "$count files renamed..."
