#!/usr/bin/python

import sys
import json

if len(sys.argv) < 4:
    print "Usage: generate_dns_records.py IP CLUSTER_A_RECORD SPECIFIC_A_RECORD [SRV_PORT SRV_ADDR...]"

ip = sys.argv[1]
cluster_a = sys.argv[2]
specific_a = sys.argv[3]
port = None
srv_addrs = []

ttl = "300"

if len(sys.argv) > 5:
    port = sys.argv[4]
    srv_addrs = sys.argv[5:]

ret = [{"rr":"A", "alias": cluster_a, "ttl": ttl,"addr": ip},
       {"rr":"A", "alias": specific_a, "ttl": ttl,"addr": ip}]

for a in srv_addrs:
    ret.append({"rr": "SRV", "alias": a, "ttl": ttl,"priority": "1", "weight": "1", "port": port, "target": specific_a})

print json.dumps(ret)
