#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file config-change
# brief manage the config changes of oai-spgw service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr and A. B. Molini  

set -ux
source $CHARM_DIR/utils/common
set_env_paths

if [ "$(config-get branch)" != "$(cat $CHARM_DIR/.branch)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get revision)" != "$(cat $CHARM_DIR/.revision)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
fi


sgw_iface=`config-get sgw-eth`
pgw_iface=`config-get pgw-eth`
ipv4_list_start=`config-get ipv4_list_start`
ipv4_list_end=`config-get ipv4_list_end`
ipv6_list=`config-get ipv6_list`
DEFAULT_DNS_IPV4_ADDRESS=`config-get DEFAULT_DNS_IPV4_ADDRESS`
DEFAULT_DNS_SEC_IPV4_ADDRESS=`config-get DEFAULT_DNS_SEC_IPV4_ADDRESS`
mme_s11_ipv4=`cat $CHARM_DIR/.mme_s11_ipv4`
pgw_masquerade=`config-get pgw_masquerade_sgi`
ue_mtu=`config-get ue_mtu`
machine_type=`virt-what`
gateway_iface_id=`ip -o -4 route show to default | awk '{print $5}'`
##############################################################################################

if [[ $gateway_iface_id == $sgw_iface ]];then
   iface_verify=`ifconfig $iface | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
   if [ -z $iface_verify ]; then
      br_check=`ifconfig br-eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`;
      eth0_ip_cfg='/etc/network/interfaces.d/eth0.cfg'
      if [ ! -z $br_check ]; then
         br_ip_mask=`ip addr | grep br-eth0 | awk '/inet/ { print $2 }'`
	     br_gateway=`route | awk '/default/ { print $2 }'`
         touch $eth0_ip_cfg
	     echo 'auto eth0' >> $eth0_ip_cfg
	     echo 'iface eth0 inet static' >> $eth0_ip_cfg
	     echo "      address $br_ip_mask" >> $eth0_ip_cfg
	     echo "      gateway $br_gateway" >> $eth0_ip_cfg
	     ifdown eth0 && ifup eth0
       fi
   fi
fi

user_conf
systemctl stop spgw || true
sysctl -w net.ipv4.ip_forward=1
$CHARM_DIR/hooks/start
