#!/bin/bash
#set -ex
DIR=/etc/hosts

juju-log "Invoking cscf-relation"
ims_cscf_zone=$(relation-get public-address)
gateway_iface_id=`ip -o -4 route show to default | awk '{print $5}'`
tunnel_net=`config-get ipv4_list_start`

if [ -z "$ims_cscf_zone" ]; then
  juju-log "No data sent yet from Cscf"
  exit 0
fi
sgw_eth=$(config-get sgw-eth)

ims_cscf_hostname=$(dig +short _sip._tcp.$ims_cscf_zone SRV | awk '{print $4}' | sed 's/.$//')

juju-log "CSFP FQDN  $ims_cscf_hostname"

ims_cscf_ip=`dig +short $ims_cscf_hostname`


if [ "$(grep  $ims_cscf_hostname /etc/hosts | cut -f2 -d' ')" = $ims_cscf_hostname ]
  then
   line_num=`grep  -n $ims_cscf_hostname /etc/hosts | cut -f1 -d:`
   sed -i "${ine_num}d" /etc/hosts
   echo "$ims_cscf_ip $ims_cscf_hostname" >> $DIR
 else 
   echo "$ims_cscf_ip $ims_cscf_hostname" >> $DIR
fi


