#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)
set -e

DIR=/etc/rebaca-test-suite
TAG_DIR=/etc/rebaca-test-suite/tags

#rm -f $DIR/tags
tags=$(config-get tags)

if [ -n $TAG_DIR/tags ]; then
        # Install the user's supplied hashes
       if [ -f $TAG_DIR/tags ]; then
         existing_tags=`cat $TAG_DIR/tags`
         juju-log "Current tags: $existing_tags"
       fi
       juju-log "Installing the tags obtained from config: $tags"
        echo -n "@$tags" > $TAG_DIR/tags
fi

private_address=$(unit-get private-address)
if [[ `dig +short $private_address` =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
    juju-log "Verifying $private_address in dns "
    DIGSHORT="dig +short"
elif [[  "$private_address" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
    DIGSHORT=echo
else
    juju-log "Unable to fetch private_address ..."
    exit 1
fi
ip=`$DIGSHORT $private_address`
  
if [ ! -z $ip ]; then
    sed -i "s/ABOT.Host.IPAddress=[^ ]*/ABOT.Host.IPAddress=$ip/" $CHARM_DIR/lib/config/config.properties
    sed -i "s#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1_MME=[^ ]*#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1_MME=$ip/24#" $CHARM_DIR/lib/config/epc_defaults.conf
    sed -i "s#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1U=[^ ]*#ABOT.ENB.ENB_IPV4_ADDRESS_FOR_S1U=$ip/24#" $CHARM_DIR/lib/config/epc_defaults.conf
else
    juju-log "IP Address of local unit not available - exiting with error"
    exit 2
fi
