#!/bin/bash

ABOT_DEPLOY_DIR=/etc/rebaca-test-suite
juju-log "Removing relation with epc"

sed -i "s/ABOT.ENB.mobile_country_code=[^ ]*/ABOT.ENB.mobile_country_code=/" ${ABOT_DEPLOY_DIR}/config/ABotConfig.properties
sed -i "s/ABOT.ENB.mobile_network_code=[^ ]*/ABOT.ENB.mobile_network_code=/" ${ABOT_DEPLOY_DIR}/config/ABotConfig.properties
sed -i "s/ABOT.ENB.mme_ip_address_ipv4=[^ ]*/ABOT.ENB.mme_ip_address_ipv4=192.168.255.255/" ${ABOT_DEPLOY_DIR}/config/ABotConfig.properties
sed -i "s/MME.SecureShell.IPAddress=[^ ]*/MME.SecureShell.IPAddress=192.168.255.255/" ${ABOT_DEPLOY_DIR}/config/ABotConfig.properties

status-set blocked "ABot blocked! Waiting for epc relation"
