#!/bin/bash

#called on every epc relation change

set -ex

mobile_country_code=`relation-get MCC`
mobile_network_code=`relation-get MNC`
mme_ip_address_ipv4=`relation-get mme_ip`
epc_running=`relation-get epc_running`

sed -i "s/ABOT.ENB.mobile_country_code=[^ ]*/ABOT.ENB.mobile_country_code=$mobile_country_code/" $CHARM_DIR/lib/config/epc_defaults.conf
sed -i "s/ABOT.ENB.mobile_network_code=[^ ]*/ABOT.ENB.mobile_network_code=$mobile_network_code/" $CHARM_DIR/lib/config/epc_defaults.conf
sed -i "s/ABOT.ENB.mme_ip_address_ipv4=[^ ]*/ABOT.ENB.mme_ip_address_ipv4=$mme_ip_address_ipv4/" $CHARM_DIR/lib/config/epc_defaults.conf
sed -i "s/MME.Host.IPAddress=[^ ]*/MME.Host.IPAddress=$mme_ip_address_ipv4/" $CHARM_DIR/lib/config/config.properties

if [ "$epc_running" == "yes" ]; then
    status-set active "Abot ready! EPC relation established, proceed to run tests..."
    exit 0
fi
status-set blocked "Abot blocked! EPC relation not established, unable to get to active state"
