#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

set -eu

abot_app=`config-get abot_app`
abot_version=`config-get abot_version`

ABOT_DEPLOY_DIR=/etc/rebaca-test-suite

(cd ${CHARM_DIR}; ./install-abot.sh -a ${abot_app} -v ${abot_version} -nc)

# Change permissions of the ABOT_DEPLOY_DIR folders 
chown -R ubuntu:ubuntu `readlink ${ABOT_DEPLOY_DIR}`

open-port 80/tcp
open-port 5000/tcp

juju-log "ABot Install complete!"
status-set maintenance "ABot installed! Waiting to start..."
