#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
set -eu

# Generate ssh key for root user 
if [ ! -f /root/.ssh/id_rsa.pub ];
   then
      ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa
      pub_key=`cat /root/.ssh/id_rsa.pub`
      echo "${pub_key}" | sed 's/\r//' >> /root/.ssh/authorized_keys
  else 
      pub_key=`cat /root/.ssh/id_rsa.pub`
      echo "${pub_key}" | sed 's/\r//' >> /root/.ssh/authorized_keys
fi

# Generate ssh key for ubuntu user 
if [ ! -f /home/ubuntu/.ssh/id_rsa.pub ];
   then
    sudo -u ubuntu bash << EOF
    ssh-keygen -t rsa -N "" -f /home/ubuntu/.ssh/id_rsa
EOF
      pub_key=`cat /home/ubuntu/.ssh/id_rsa.pub`
      echo "${pub_key}" | sed 's/\r//' >> /home/ubuntu/.ssh/authorized_keys
  else
      pub_key=`cat /home/ubuntu/.ssh/id_rsa.pub`
      echo "${pub_key}" | sed 's/\r//' >> /home/ubuntu/.ssh/authorized_keys
fi

status-set maintenance "ABot updated! Setup relations to get into active state..."
