#!/bin/bash
# This hook is executed each time a charm is upgraded after the new charm
# contents have been unpacked
# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed
set -eu

abot_app=`config-get abot_app`
abot_version=`config-get abot_version`

ABOT_DEPLOY_DIR=/etc/rebaca-test-suite

(cd ${CHARM_DIR}; ./install-abot.sh -a ${abot_app} -v ${abot_version} -nc)

# Change permissions of the ABOT_DEPLOY_DIR folders 
chown -R ubuntu:ubuntu `readlink ${ABOT_DEPLOY_DIR}`

if [ ! -f ~/.ssh/id_rsa.pub ];
   then
      ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
      pub_key=`cat ~/.ssh/id_rsa.pub`
      echo "$pub_key" | sed 's/\r//' >> ~/.ssh/authorized_keys
fi

open-port 80/tcp

juju-log "ABot update complete!"
status-set maintenance "ABot updated! Reset relations to get into active state"
